/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a full install. It is committed here so
// the scaffold type-checks immediately after dependencies are installed.

